/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indesapres.grafico;

import indesapres.logica.ServiciosDB;
import indesapres.modelos.Deducciones;
import indesapres.modelos.Prestamos;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

/**
 *
 * @author Oscar Mendez
 */
public final class BalanceGeneral extends javax.swing.JFrame {

    /**
     * Creates new form BalanceGeneral
     */
    public BalanceGeneral() {
        initComponents();
        setearinformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("BALANCE GENERAL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Prestamos", "Capital + interes", "Deducciones", "Abono Capital", "Interes ganado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton1.setText("Generar Documento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        crearTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BalanceGeneral().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void setearinformacion() {
        try {
            ServiciosDB service = new ServiciosDB();
            Prestamos pres;
            float sumaPrestamos = (float) 0.0;
            float sumaDeducciones = (float) 0.0;
            float sumaCapital = (float) 0.0;
            float sumaCapitalded = (float) 0.0;
            float sumaInteresded = (float) 0.0;
            Deducciones ded;
            ArrayList<Prestamos> depts;
            depts = (ArrayList<Prestamos>) service.findAllPrestamos();
            ArrayList<Deducciones> deptsd;
            deptsd = (ArrayList<Deducciones>) service.findAllDeducciones();
            for (int x = 0; x < depts.size(); x++) {
                float prestamos = depts.get(x).getPrestamos();
                float capital = depts.get(x).getCapitalinteres();
                sumaPrestamos = sumaPrestamos + prestamos;
                sumaCapital = sumaCapital + capital;
            }
            for (int x = 0; x < deptsd.size(); x++) {
                float deducciones = deptsd.get(x).getDeduccion();
                sumaDeducciones = sumaDeducciones + deducciones;
                String idPrestamo = deptsd.get(x).getIdPrestamo();
                pres = service.findByIdPrestamos(idPrestamo);
                float capitalded = pres.getPrestamos() / (pres.getPlazo() * 2);
                float interesded = pres.getTotalinteres() / (pres.getPlazo() * 2);
                sumaCapitalded = sumaCapitalded + capitalded;
                sumaInteresded = sumaInteresded + interesded;
            }
            jTable1.setValueAt(formatNumber(sumaPrestamos), 0, 0);
            jTable1.setValueAt(formatNumber(sumaDeducciones), 0, 2);
            jTable1.setValueAt(formatNumber(sumaCapital), 0, 1);
            jTable1.setValueAt(formatNumber(sumaCapitalded), 0, 3);
            jTable1.setValueAt(formatNumber(sumaInteresded), 0, 4);

        } catch (SQLException ex) {
            Logger.getLogger(BalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void agregarFilas() {
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Object nuevo[] = {0, 0.0, 0.0, 0.0, 0.0};
        temp.addRow(nuevo);
    }

    public void crearTable() {
        FileOutputStream outStream = null;
        try {
            Date date = new Date();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");;
            String path = "template.docx";
            XWPFDocument document = new XWPFDocument(new FileInputStream(new File(path)));
            String parrafo1 = "Balance General a la Fecha " + format.format(date);

            XWPFParagraph paragraph1 = document.createParagraph();
            XWPFRun run1 = paragraph1.createRun();
            run1.setFontSize(12);
            run1.setFontFamily("Calibri");
            run1.setText(parrafo1);
            paragraph1.setAlignment(ParagraphAlignment.LEFT);

            XWPFTable tableOne = document.createTable();
            XWPFTableRow tableOneRowOne = tableOne.getRow(0);
            tableOneRowOne.getCell(0).setText("Prestamos");
            tableOneRowOne.addNewTableCell().setText("Capital + interes");
            tableOneRowOne.addNewTableCell().setText("Recuperado");
            tableOneRowOne.addNewTableCell().setText("Abono Capital");
            tableOneRowOne.addNewTableCell().setText("Interes Ganado");
            XWPFTableRow tableRow1 = tableOne.createRow();
            String prestamo = String.valueOf(jTable1.getValueAt(0, 0));
            String capitalinteres = String.valueOf(jTable1.getValueAt(0, 1));
            String deducciones = String.valueOf(jTable1.getValueAt(0, 2));
            String capital = String.valueOf(jTable1.getValueAt(0, 3));
            String interes = String.valueOf(jTable1.getValueAt(0, 4));
            tableRow1.getCell(0).setText(prestamo);
            tableRow1.getCell(1).setText(capitalinteres);
            tableRow1.getCell(2).setText(deducciones);
            tableRow1.getCell(3).setText(capital);
            tableRow1.getCell(4).setText(interes);
            outStream = new FileOutputStream("C:\\Users\\Oscar Mendez\\Documents\\INDESAPRES\\Documentos Indesa\\Balance General.docx");
            document.write(outStream);
            outStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String formatNumber(float cantidad){
        String res;
        DecimalFormat formateador = new DecimalFormat("###,###.##");
        res = formateador.format(cantidad);
        return res;
    }

}
